### ISSUE TITLE
FEATURE: detect copy

### ISSUE THREAD

**Issue by jccguimaraes** [nju33/atom-colorio#2]
Hey, this is a great plugin.
Ace work.

But it would be nice to detect the copy of a color and automatically add it to the input.

**Comment by nju33** [comment]
Thank you @jccguimaraes  for a good idea! 😆
I would like to fix it soon.

**Comment by nju33** [comment]
Hi, @jccguimaraes 😀
I released colorio@v0.2.0 now 🎉, please update it if you want.

**Comment by jccguimaraes** [comment]
@nju33 fantastic! great feature. thanks
